# For more information please visit: https://github.com/SzczepanLeon/esphome-components
# If you want, you can buy me a coffee:
#     https://www.buymeacoffee.com/szczepan
#     https://buycoffee.to/szczepanleon

substitutions:
  name: "ultimatereader"
  friendly_name: "Ultimate Reader"


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  platformio_options:
    upload_speed: 921600
    board_build.arduino.ldscript: esp32s3_out.ld
    board_build.arduino.partitions: default.csv
    board_build.arduino.memory_type: qio_qspi
  project:
    name: wmbus.UltimateReader
    version: "1.2"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf

external_components:
  - source: github://wM-Bus/UltimateReader@version_5
    refresh: 0d

dashboard_import:
  package_import_url: github://wM-Bus/UltimateReader/UltimateReader.yaml@version_5
  import_full_config: true

logger:
  id: component_logger
  level: DEBUG
  baud_rate: 115200

wifi:
  ap:

captive_portal:

time:
  - platform: homeassistant

api:

web_server:
  version: 3 

spi:
  clk_pin:
    number: GPIO5
    ignore_strapping_warning: true
  mosi_pin: GPIO27
  miso_pin: GPIO19

socket_transmitter:
  id: my_socket
  ip_address: 10.0.0.22
  port: 7227
  protocol: UDP

mqtt:
  broker: test.mosquitto.org
  port: 1883
  client_id: some_client_id

wmbus_radio:
  radio_type: SX1276
  cs_pin: GPIO18
  reset_pin: GPIO14
  irq_pin: GPIO35
  on_frame:
    - then:
        - repeat:
            count: 3
            then: 
              - output.turn_on: status_led
              - delay: 100ms
              - output.turn_off: status_led
              - delay: 100ms
    - mark_as_handled: True
      then:
        - mqtt.publish:
            topic: wmbus-test/telegram_rtl
            payload: !lambda return frame.as_rtlwmbus();
    - mark_as_handled: True
      then:
        - wmbus_radio.send_frame_with_socket:
            format: hex

wmbus_meter:
  - id: electricity_meter
    meter_id: 0x0101010101
    type: amiplus
    key: SomeKey
  - id: heat_meter
    meter_id: 0x101010101
    type: hydrocalm3
    on_telegram:
      then:
        - wmbus_meter.send_telegram_with_mqtt:
            topic: wmbus-test/telegram

output:
  - platform: gpio
    id: vext_output
    pin: GPIO21
  - platform: gpio
    id: oled_reset
    pin: GPIO16
    inverted: True
  - platform: gpio
    id: status_led
    pin: GPIO25

sensor:
  - platform: uptime
    type: seconds
    name: Ultimate Reader uptime

  - platform: wmbus_meter
    parent_id: heat_meter
    field: total_heating_kwh
    device_class: energy
    name: Zużycie energii cieplnej
    accuracy_decimals: 4
    state_class: total_increasing

  - platform: wmbus_meter
    parent_id: electricity_meter
    field: current_power_consumption_kw
    name: Moc aktualna
    accuracy_decimals: 0
    device_class: power
    unit_of_measurement: W
    state_class: measurement
    filters:
      - multiply: 1000

  - platform: wmbus_meter
    parent_id: electricity_meter
    field: total_energy_consumption_kwh
    name: Zużycie energii
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: wmbus_meter
    parent_id: electricity_meter
    field: rssi
    name: Electricity Meter RSSI